version: '3.8'

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # API
      - "8000:8000"
      # Web Client
      - "3000:5173"
    depends_on:
      - db
      - redis
      - aspire-dashboard

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=lenny
      - POSTGRES_PASSWORD=lenny
      - POSTGRES_DB=lenny
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
